language: node_js
node_js:
- 12.18.0
install:
- npm install
script:
- npm run deploy
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: "u1ZxJLX24eV8jI4OR1Nosog/y8zjXJ4Kch84ZBoAKyl7lxnAO3avIk7wJQQiSou1y4BYuPg6h0rCwqQVpa/SrhL2zpYYSjuc8BDUOG6JZIM5Z/zTV/wWlXP9KQT9/O/V6lHIBltdXM1wqCA9s9iPycWijfrKs2l5+rwMNsaKgReMzsFyykDm0kh3mLWLNy2Ir1vpYGGp2LAvybeEpmaX/1PCXDh3ABzdqOYBVOZlZoGJfDQyOfr0QHUDtUZNm4Emm0MyNmO3NT5KW4KrJWZM35czHbhIHLP3z6FM0cNIDyln8mDGeeBjs234WJ+uZ95mzDiytYwiDS3XcrTVzAlFmS0k6LnxuIHwiDLP5jUQ9o2c1l35wKyoBxihhQaplr1yUgjYpkqH6c7Y3TsnAvu2+DPUmE/q8VoSof9VcPdN6KP9UQIgWEle2KLCDdB2Da0yzhcx3ZgcdMV1DH6s6QLS0DT4XR5dwjOLFqNYGdpveXMHKkUB/QVx/KB4Cg/UITNJGDbiBJJ7bKMVX91hbYlsJSdwPOPmrdFNCk988dSX60+HnxJ17OF54GCMy4zaSs6vRjAZEka6fJKVjRAq2EUkWT75jFJg6ik1tqENizBtM++9ZK2YNJw4gikFCzSLRlLPTAIWRZR5Y8rqDgmeHJB8dD6XAXqDbWoyq72CGkcvZUs="
  app:
    master: next-app-boilerplate
