language: node_js
node_js:
- 12
install:
- npm install
script:
- npm run build
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: NXjflyQj4VJQG2DeBsYgDg9LVaHKwRhT9NRH6xg1uuSkiGjcEyQz9mBQZQobEko+v5MnKSrpkFy/pbhOS+RtBh73egXr69yJLUUcNkp15NKHGW6/uLadZENkRG49Omi3eATJvTaq/eLsUzRvd3BhnW0nUJhEEC0v3LggM1rsJsLzSyzvI6D0eHTP4ljytYrWFkiJCkUlUU6EmtpteEFu8pFEsMX0iFDe0qRP0vNWF3juPPIUve6EEIMmm2o2k8ARa4BDdUJA8qVz58Z7rQZ55zCOMclu4T4dFqHUGgYl3I7ssBQP0IsxhpjFgNJr8VeO5HAlgKArrBwBgbo3Ws3XWPTPoPRQ4L05P0Lm8fDWCx6HXJPDOI1O4iLipDESjDh0zb9l0H/HIVLu+tEEAzHfoX7+gBhDyqMgsTLD1paGkpC+/dCDUIMj08HN8vL6n3dk3CTN+PCx4OYVfdg9WrtGRUq4kDuAqzqqRjiB/TkaXKblAFVz7j6MxmDHw18FE0lQeszcJKkMXpp+TtZO9uDJ3IM4UGrVbbhhcYdE536TVhL7E6rEAo29aJVPLkASPUNjXAdkmev3vVUID2T2zwU+yHLnAhOHmIABSXpSg05wnfNE/nYB6c06+FQjPEb3VLs2TDsZPr7Y7LXvPijNlPv2YbDw2EiJdGnLmp+Id2biP10=
  app:
    master: next-app-boilerplate
