language: node_js
node_js:
- 12.18.0
install:
- npm install
script:
- npm run build
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: vJj6cFATcf50L9QgO4xFI/eK1uBWObbr1QGyyBZShWLbwmhFwwsmqxfZWIKFtgSw9wGQEEEu9slsQ+N3gAJmmFd8Duj1Z0cY4W+6EpEmtPo159bTtqUktVvDDNIyVQcxeXtouO5Y+CY7CWtRBlkdRvJF0iLfhcU1L0aYXC16yI3T3k4Rxv/MHHUbyAaD+eK1tyv2R/aqd4KqhR6m3yd6e2Rn9eYQGChEbsTC54ghk+EMcB/TpNmOs0yGjlALm3xOr640lFLB41okbl80gLtXnsdrJRFeid4YgZNGdMQ83rNdwknJrZnI95+mP/cIincL8CbOvaSUZg2FRYv0ax78E1iCOWgEm8l/AQ/l1zkmDdlYDgwiNfp9JRbuhVMT+oiwnp1HSNm6qZUi+TortnVwKpqzF1WOsp5Vzr+ya4+He0E2lRFjiDG715rKHGfJqG7i5c1R1UtZUJPF+kneKebk3gF1CdMZRItEU4NnHLgwx9PJ7GZWBQ8+Z7a7JZjigruWqkwqSRPWSsf3tuPrUUWL5sZ4aIuF45b828O6lH0K0idiMaI236UQePo3BXgzYQEe1lsQeYPEQ/uh4s+9Z1bddPtl2mUA/h5UMnEsziYNl3dhSCQW40EXhQ7MNOFfAuu60oZULJiqDDIHs06aq45dVK83I7T7GZz38WqX+HgUlmM=
  app:
    master: next-app-boilerplate
