language: node_js
node_js:
- 12
install:
- npm install
script:
- npm run build
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: G7A/k+KS436z1CXC/dDzXQvd5JAvq/VN/IOEQvykTEjgtpZDY0nulv/6doNzaFPeqwzXgzKb2E4tJKR6i025tNn0z3IUUXqOgfY80N/oMbZcae2Ud0BHEXxu/Jh4zzeaGyIs4bLi4GVhgTJQzP9Htt5u1hvdv4k0yw3gw865jmU5SosTSX7kfWJPHLq1pnu1fo2ANuVo194aZT3l1p3T+B9MKVna0Z3cp54dW2McmVa+mxCXC/L3Z2jgzgFKTiitvmlrPsqjvPs306Rw3KvZB4tIdrippjDuzVZGYaSlaWJAD5iTyg2jDhkiwOfcS649HBjjRYOAYrZS7JRUxd9DOmXfzhdXCrA5eBJb8ADc9ESTM1FAhOfxWJtB/mgn10zBuPKk69DzxXPKUFItyNTJa8SqbZD6U74DF8kzOckSInZN4zjQWSWIr3oSTLkHHsvc5NAhDj38idc8qXlHh7DdPc+Y0kvCGDJTDu5ZmE9gUdIL3vou9dxBbLaYDmGqC9rtRBhmh+4YWuUkbUernOHDNID81Yeh7JTSfnt7OJ5xkTjLNpNIHmzsFF14kk/Y9WvDyin7LLwIA1+FkM+1dW+iXqAhSbrrdYJZ802TX8NzfLkJCsG5aI7XH34U+WN/yFGmNrVe3MjftZ2f2gnH3rIqGMhoidxKwxZrh0PHH1z9Sig=
  app:
    master: next-app-boilerplate
