language: node_js
node_js:
- 12
install:
- npm install
script:
- npm run build
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: KhX5J6BOaz/t/QR5q95VeRtRc/PWshe9q/R3PQqVFc4KUTcX4nT9I1M/HnV7qy69ZsZwd9Cqo3UNVRwIoX6e/j2OMUC6BdCmJrq80mQeZQ2VRzp0KzEaKSS/pKx/vbzVofFbzL2+HzJucm0qp5ITeni2tGUmgf85fOUTfdwf3jExHyhe7yQf9aOsImkg0Ga/UgEaARbaC7SghPafXtel6/EHzTKv4ZUNNUQTXLAxvymwCG7dyNXP/ZelEh4eyziuEkJxyFIEzkCtyPlYI6o81fc6nBEUno2DRUfGG6xtJvjzLYRPvMG9a391sHPJG+HCAtlDgqi4AW1RNfQSYyOx0QL+91Vq1RMrOTMfLQFTAyL27Hma0sBJKNX92NqIrMstbjBU5G7Hn32wKaVPrT+9BZpDUwl63pqCixInN7I/NF6+pAacKKkdkeh1Q35OjT5FLsXPh0MHOuIe2OmBrXnjM1OsdAY4YYUYH2iqJfYACCmm9Eby3jvvajoBOT6V5I/h0QeYj207AnMWYpbPG8zgUDP7pQoNX57+LsuQTAQCgENGbJ9/njdUimxHStL2xhqQ8ad1q5An5o7ju8B6nxKcwN16r+Sz3qAkg1ja5zuz5HZDhGFkKDhrM5yCEFG6a+K5WAKIV0BCQ+0iBayMYdVEfZjgrcrZnO0chccbuW5Odr8=
  app:
    master: next-app-boilerplate
